;Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
;By starting with 1 and 2, the first 10 terms will be:

;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;By considering the terms in the Fibonacci sequence whose values do not exceed four million,
;find the sum of the even-valued terms.
;
(define (fib-even-sum count)
  (fib-iter 1 1 count 0))

(define (fib-iter a b count result)
  (if (> a count)
	result
	(if (even? a)
	  (fib-iter (+ a b) a count (+ a result))
	  (fib-iter (+ a b) a count result))))

;ans
(fib-even-sum 4000000)

